# Generated by Django 3.2.7 on 2021-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ManyToManyField(related_name='organization_clients', to='Organizations.Organization', verbose_name='Organization'),
        ),
    ]
