# Generated by Django 3.2.6 on 2021-08-25 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_auto_20210825_1003'),
        ('Clients', '0003_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_clients', to='Organizations.organization', verbose_name='Organization'),
        ),
    ]
