# Generated by Django 3.2.7 on 2021-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_auto_20211123_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated_at'),
        ),
        migrations.AddField(
            model_name='organization',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
