# Generated by Django 3.2.7 on 2021-11-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='products',
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_product_order', to='Market.product', verbose_name='Product'),
        ),
    ]
