# Generated by Django 3.2.7 on 2021-10-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='patronymic',
            new_name='second_name',
        ),
    ]
