# Generated by Django 4.0.1 on 2022-02-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_mygroup_options_alter_mygroup_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='mygroups_users', to='Users.MyGroup', verbose_name='Groups'),
        ),
    ]
