# Generated by Django 4.0.1 on 2022-02-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_services_alter_user_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='mygroups_users', to='Users.MyGroup', verbose_name='Groups'),
        ),
    ]
