# Generated by Django 4.0.1 on 2022-02-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='sessions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
