# Generated by Django 4.0.1 on 2022-02-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_services_alter_user_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.IntegerField(null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='code_expired_at',
            field=models.DateTimeField(null=True, verbose_name='Code expired time'),
        ),
    ]
