# Generated by Django 4.0.1 on 2022-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('data', models.JSONField(blank=True, null=True)),
                ('device', models.CharField(max_length=150, verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Session client',
                'verbose_name_plural': 'Sessions clients',
                'db_table': 'session_client',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Session_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('data', models.JSONField(blank=True, null=True)),
                ('device', models.CharField(max_length=150, verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Session user',
                'verbose_name_plural': 'Sessions users',
                'db_table': 'session_user',
                'ordering': ['-updated_at'],
            },
        ),
    ]
