# Generated by Django 3.2.7 on 2021-10-21 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sessions', '0001_initial'),
        ('Clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='session_client',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='Clients.client', verbose_name='Client'),
        ),
        migrations.AlterUniqueTogether(
            name='session_user',
            unique_together={('user', 'device')},
        ),
        migrations.AlterUniqueTogether(
            name='session_client',
            unique_together={('client', 'device')},
        ),
    ]
