# Generated by Django 3.2.7 on 2021-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_client',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session_user',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
