# Generated by Django 3.2.7 on 2021-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20211123_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
