# Generated by Django 3.2.7 on 2021-10-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0003_alter_organization_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('price', models.FloatField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_service_price', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'ServicePrice',
                'verbose_name_plural': 'ServicePrices',
                'db_table': 'ServicePrice',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_device_type', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'DeviceType',
                'verbose_name_plural': 'DeviceTypes',
                'db_table': 'DeviceType',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_device_model', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'DeviceModel',
                'verbose_name_plural': 'DeviceModels',
                'db_table': 'DeviceModel',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_device_maker', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'DeviceMaker',
                'verbose_name_plural': 'DeviceMakers',
                'db_table': 'DeviceMaker',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type_device_kit', to='Handbook.devicetype', verbose_name='DeviceType')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_device_kit', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'DeviceKit',
                'verbose_name_plural': 'DeviceKits',
                'db_table': 'DeviceKit',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_device_defect', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'DeviceDefect',
                'verbose_name_plural': 'DeviceDefects',
                'db_table': 'DeviceDefect',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_device_appearance', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'DeviceAppearance',
                'verbose_name_plural': 'DeviceAppearances',
                'db_table': 'DeviceAppearance',
                'ordering': ['-updated_at'],
            },
        ),
    ]
