# Generated by Django 3.2.7 on 2021-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceappearance',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedefect',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicekit',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemaker',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
