# Generated by Django 3.2.7 on 2021-10-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handbook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='model',
            field=models.CharField(choices=[('ProductOrder', 'ProductOrder'), ('WorkDone', 'WorkDone'), ('SaleOrder', 'SaleOrder'), ('Order', 'Order'), ('OrderHistory', 'OrderHistory')], max_length=150, verbose_name='Model name'),
        ),
    ]
