# Generated by Django 3.2.7 on 2021-10-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handbook', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicekit',
            old_name='device_type',
            new_name='devicetype',
        ),
    ]
