# Generated by Django 3.2.7 on 2021-10-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_auto_20211012_0952'),
        ('Organizations', '0005_auto_20211012_0952'),
        ('Handbook', '0002_auto_20211012_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('data', models.JSONField(blank=True, null=True)),
                ('method', models.CharField(max_length=150, null=True, verbose_name='Method')),
                ('process', models.CharField(max_length=150, verbose_name='Process')),
                ('model', models.CharField(max_length=150, verbose_name='Model name')),
            ],
            options={
                'verbose_name': 'ActionHistory',
                'verbose_name_plural': 'ActionHistorys',
                'db_table': 'ActionHistory',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('data', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('action_history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_history_order_history', to='Handbook.actionhistory', verbose_name='Action history')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_history', to='Orders.order', verbose_name='Order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_order_history', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'OrderHistory',
                'verbose_name_plural': 'OrderHistories',
                'db_table': 'OrderHistory',
                'ordering': ['-updated_at'],
            },
        ),
    ]
