# Generated by Django 4.0.1 on 2022-02-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_alter_mprovider_service_and_more'),
        ('Handbook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceappearance',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_deviceappearance', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='devicedefect',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_devicedefect', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='devicekit',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_devicekit', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='devicemaker',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_devicemaker', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_devicemodel', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_devicetype', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_devicehistory', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_deviceprice', to='Organizations.service', verbose_name='Service'),
        ),
    ]
