# Generated by Django 3.2.7 on 2021-10-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handbook', '0004_alter_actionhistory_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionhistory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'ActionHistory', 'verbose_name_plural': 'ActionHistories'},
        ),
    ]
