# Generated by Django 3.2.7 on 2021-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handbook', '0005_alter_actionhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='model',
            field=models.CharField(choices=[('0', 'ProductOrder'), ('1', 'WorkDone'), ('2', 'Sale'), ('3', 'Order'), ('4', 'OrderHistory')], max_length=150, verbose_name='Model name'),
        ),
    ]
