# Generated by Django 3.2.7 on 2021-10-22 11:49

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_member',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization_member',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='organization_member',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='organization_member',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization_member',
            name='pass_number',
            field=models.CharField(default=1, max_length=6, verbose_name='Passport number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization_member',
            name='pass_series',
            field=models.CharField(default=1, max_length=4, verbose_name='Passport series'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization_member',
            name='patronymic',
            field=models.CharField(default=1, max_length=150, verbose_name='Patronymic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization_member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='organization_member',
            name='surname',
            field=models.CharField(default=1, max_length=150, verbose_name='Surname'),
            preserve_default=False,
        ),
    ]
