# Generated by Django 3.2.7 on 2021-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_auto_20211022_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization_member',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='organization_member',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='organization_member',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='organization_member',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization_member',
            name='pass_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Passport number'),
        ),
        migrations.AlterField(
            model_name='organization_member',
            name='pass_series',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Passport series'),
        ),
        migrations.AlterField(
            model_name='organization_member',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Surname'),
        ),
    ]
