# Generated by Django 3.2.7 on 2021-10-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_alter_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
