# Generated by Django 4.0.1 on 2022-02-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_alter_role_unique_together_remove_role_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprovider',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_mprovider', to='Organizations.service', verbose_name='Service'),
        ),
    ]
