# Generated by Django 3.2.7 on 2021-10-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_auto_20211022_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_member',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Second name'),
        ),
    ]
