# Generated by Django 4.0.1 on 2022-02-21 14:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Organizations', '0005_alter_mprovider_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mygroup_organizations', to='Organizations.organization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='mygroup_permissions', to='auth.Permission', verbose_name='permissions')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mygroup_services', to='Organizations.service')),
            ],
            options={
                'verbose_name': 'MyGroup',
                'verbose_name_plural': 'MyGroups',
                'db_table': 'mygroup',
                'permissions': [('change_user_group', 'Can change user group')],
                'unique_together': {('name', 'organization', 'service')},
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
