# Generated by Django 3.2.7 on 2021-10-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_auto_20211012_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='prefix',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Prefix'),
            preserve_default=False,
        ),
    ]
