# Generated by Django 4.0 on 2021-12-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0006_alter_custompermission_id_alter_mprovider_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set(),
        ),
    ]
