# Generated by Django 4.0 on 2021-12-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0007_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_member',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Avatar'),
        ),
    ]
