# Generated by Django 4.0 on 2021-12-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0009_organization_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MProvider',
        ),
    ]
