# Generated by Django 4.0 on 2021-12-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0010_delete_mprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('data', models.JSONField(blank=True, null=True)),
                ('site', models.CharField(max_length=300, verbose_name='Site')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_mprovider', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'MProvider',
                'verbose_name_plural': 'MProviders',
                'db_table': 'mprovider',
                'ordering': ['-updated_at'],
            },
        ),
    ]
