# Generated by Django 4.0 on 2021-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0011_mprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprovider',
            name='data',
            field=models.JSONField(default={'address': 'address', 'count': 'available_all', 'name': 'name', 'price': 'price', 'provider_site': 'url', 'url_photo': 'picture', 'url_product': 'url'}, verbose_name='Data'),
        ),
    ]
