# Generated by Django 4.0 on 2021-12-25 21:11

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBusket',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(verbose_name='Count')),
                ('price', models.FloatField(verbose_name='Price')),
                ('products', djongo.models.fields.JSONField(verbose_name='Products')),
                ('author', djongo.models.fields.JSONField(verbose_name='Author')),
                ('providers', djongo.models.fields.JSONField(verbose_name='Providers')),
                ('organization', djongo.models.fields.JSONField(verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'MBusket',
                'verbose_name_plural': 'MBuskets',
                'db_table': 'mbusket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCourier',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', djongo.models.fields.JSONField(verbose_name='Courier')),
                ('organization', djongo.models.fields.JSONField(verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'MCourier',
                'verbose_name_plural': 'MCouriers',
                'db_table': 'mcourier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MOrder',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(verbose_name='Count')),
                ('count_success', models.IntegerField(default=0, verbose_name='Count Success')),
                ('price', models.FloatField(verbose_name='Price')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('description', models.CharField(max_length=5000, verbose_name='Description')),
                ('comment', models.CharField(max_length=1000, verbose_name='Comment')),
                ('products', djongo.models.fields.JSONField(verbose_name='Products')),
                ('courier', djongo.models.fields.JSONField(verbose_name='Courier')),
                ('providers', djongo.models.fields.JSONField(verbose_name='Providers')),
                ('author', djongo.models.fields.JSONField(verbose_name='Author')),
                ('organization', djongo.models.fields.JSONField(verbose_name='Organization')),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'MOrder',
                'verbose_name_plural': 'MOrders',
                'db_table': 'morder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MProduct',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('price', models.FloatField(verbose_name='Price')),
                ('price_opt', models.FloatField(verbose_name='Wholesale price')),
                ('url_product', models.CharField(max_length=300, verbose_name='Product url')),
                ('url_photo', models.CharField(max_length=300, verbose_name='Photo url')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('provider_site', models.CharField(max_length=300, verbose_name='MProvider')),
                ('organization', djongo.models.fields.JSONField(verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'MPoduct',
                'verbose_name_plural': 'MPoducts',
                'db_table': 'mproduct',
                'ordering': ['-created_at'],
            },
        ),
    ]
