# Generated by Django 4.0 on 2021-12-19 14:23

import Marketplace.models
import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import restapi.views


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCourier',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', djongo.models.fields.JSONField(verbose_name='Courier')),
                ('organization', djongo.models.fields.JSONField(verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'MCourier',
                'verbose_name_plural': 'MCouriers',
                'db_table': 'mcourier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MProduct',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('price_opt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wholesale price')),
                ('url_product', models.URLField(validators=[django.core.validators.URLValidator, restapi.views.script_injection], verbose_name='Product url')),
                ('url_photo', models.URLField(validators=[django.core.validators.URLValidator, restapi.views.script_injection], verbose_name='Photo url')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('provider_site', models.CharField(max_length=300, verbose_name='MProvider')),
                ('organization', djongo.models.fields.JSONField(verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'MPoduct',
                'verbose_name_plural': 'MPoducts',
                'db_table': 'mproduct',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MOrder',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('description', models.CharField(max_length=5000, verbose_name='Description')),
                ('comment', models.CharField(max_length=1000, verbose_name='Comment')),
                ('courier', djongo.models.fields.EmbeddedField(model_container=Marketplace.models.MCourier, verbose_name='Courier')),
                ('author', djongo.models.fields.JSONField(verbose_name='Author')),
                ('organization', djongo.models.fields.JSONField(verbose_name='Organization')),
                ('products', djongo.models.fields.ArrayReferenceField(on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='Marketplace.mproduct', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'MOrder',
                'verbose_name_plural': 'MOrders',
                'db_table': 'morder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MBusket',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(verbose_name='Count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('author', djongo.models.fields.JSONField(verbose_name='Author')),
                ('organization', djongo.models.fields.JSONField(verbose_name='Organization')),
                ('products', djongo.models.fields.ArrayReferenceField(on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='Marketplace.mproduct', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'MBusket',
                'verbose_name_plural': 'MBuskets',
                'db_table': 'mbusket',
                'ordering': ['-created_at'],
            },
        ),
    ]
