# Generated by Django 4.0.1 on 2022-02-07 11:31

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcourier',
            old_name='courier',
            new_name='member',
        ),
        migrations.AddField(
            model_name='mbusket',
            name='service',
            field=djongo.models.fields.JSONField(default=1, verbose_name='Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcourier',
            name='service',
            field=djongo.models.fields.JSONField(default=1, verbose_name='Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morder',
            name='service',
            field=djongo.models.fields.JSONField(default=1, verbose_name='Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mproduct',
            name='service',
            field=djongo.models.fields.JSONField(default=1, verbose_name='Service'),
            preserve_default=False,
        ),
    ]
