# Generated by Django 4.0 on 2021-12-25 11:28

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbusket',
            name='providers',
            field=djongo.models.fields.JSONField(default=1, verbose_name='Providers'),
            preserve_default=False,
        ),
    ]
