# Generated by Django 3.2.7 on 2021-10-10 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0006_auto_20211008_1135'),
        ('Handbook', '0001_initial'),
        ('Organizations', '0004_alter_role_name'),
        ('Clients', '0007_alter_clientcard_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('cash', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cash')),
                ('account_money', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Account money')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_cashbox', to='Organizations.organization', verbose_name='Organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_cashbox', to='Organizations.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Cashbox',
                'verbose_name_plural': 'Cashboxes',
                'db_table': 'Cashbox',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('code', models.CharField(max_length=150, null=True, verbose_name='Code')),
                ('barcode', models.CharField(max_length=150, null=True, verbose_name='Barcode')),
                ('purchase_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Purchase price')),
                ('sale_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale price')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count')),
                ('supplier', models.CharField(max_length=150, verbose_name='Supplier')),
                ('irreducible_balance', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('is_deferred', models.BooleanField(default=False, verbose_name='Deferred')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_purchase', to='Market.cashbox', verbose_name='Purchase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_purchase', to='Organizations.organization', verbose_name='Organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_purchase', to='Organizations.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'Purchase',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('cash', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cash')),
                ('card', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Card')),
                ('bank_transfer', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bank transfer')),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_sale', to='Market.cashbox', verbose_name='Purchase')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_card_sale', to='Clients.clientcard', verbose_name='ClientCard')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_sale', to='Organizations.organization', verbose_name='Organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_sale', to='Organizations.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'Sale',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_work_done', to='Orders.order', verbose_name='Order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_work_done', to='Organizations.organization', verbose_name='Organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_work_done', to='Organizations.service', verbose_name='Service')),
                ('service_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_price_work_done', to='Handbook.serviceprice', verbose_name='ServicePrice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_work_done', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'WorkDone',
                'verbose_name_plural': 'WorkDones',
                'db_table': 'WorkDone',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_transaction', to='Market.cashbox', verbose_name='Cashbox')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_transaction', to='Organizations.organization', verbose_name='Organization')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_transaction', to='Market.purchase', verbose_name='Purchase')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbox_sale', to='Market.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transaction',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product_order', to='Orders.order', verbose_name='Order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_product_done', to='Organizations.organization', verbose_name='Organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_product_order', to='Market.product', verbose_name='Product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_product_order', to='Organizations.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'ProductOrder',
                'verbose_name_plural': 'ProductOrders',
                'db_table': 'ProductOrder',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_product', to='Market.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_product', to='Organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_product', to='Market.purchase', verbose_name='Purchase'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_product', to='Market.sale', verbose_name='Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_product', to='Organizations.service', verbose_name='Service'),
        ),
    ]
