# Generated by Django 3.2.7 on 2021-10-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_auto_20211017_1326'),
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_product_order', to='Orders.order', verbose_name='Order'),
        ),
    ]
