# Generated by Django 4.0.1 on 2022-02-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdone',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_work_done', to='Orders.order', verbose_name='Order'),
        ),
    ]
