# Generated by Django 4.0.1 on 2022-02-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
        ('Market', '0002_initial'),
        ('Handbook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_work_done', to='Organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='workdone',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_work_done', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='workdone',
            name='service_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_price_work_done', to='Handbook.serviceprice', verbose_name='ServicePrice'),
        ),
    ]
