# Generated by Django 3.2.7 on 2021-10-21 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Market', '0002_workdone_order'),
        ('Organizations', '0001_initial'),
        ('Handbook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_work_done', to='Organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='workdone',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_work_done', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='workdone',
            name='service_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_price_work_done', to='Handbook.serviceprice', verbose_name='ServicePrice'),
        ),
    ]
