# Generated by Django 3.2.7 on 2021-10-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_alter_productorder_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='product',
            new_name='products',
        ),
    ]
