# Generated by Django 3.2.7 on 2021-10-10 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='account_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Account money'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='irreducible_balance',
            field=models.FloatField(null=True, verbose_name='Irreducible balance'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Sale price'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_purchase', to='Market.cashbox', verbose_name='Cashbox'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bank_transfer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Bank transfer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator('0.0')], verbose_name='Price'),
        ),
    ]
