# Generated by Django 3.2.7 on 2021-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
