# Generated by Django 3.2.7 on 2021-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20211010_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workdone',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
