# Generated by Django 4.0.1 on 2022-02-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_alter_mprovider_service_and_more'),
        ('Market', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cashbox', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='product',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_product', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_product_order', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_purchase_request', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_sale_order', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_sale_product', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_work_done', to='Organizations.service', verbose_name='Service'),
        ),
    ]
