# Generated by Django 4.0.1 on 2022-02-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_alter_mprovider_service_and_more'),
        ('Market', '0005_alter_cashbox_service_alter_product_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_transaction', to='Organizations.service', verbose_name='Service'),
        ),
    ]
