# Generated by Django 3.2.7 on 2021-10-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_transaction_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='body',
        ),
    ]
