# Generated by Django 3.2.7 on 2021-10-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_auto_20211012_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_product', to='Market.purchase', verbose_name='Purchase'),
        ),
    ]
