# Generated by Django 3.2.7 on 2021-10-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_alter_product_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_purchase', to='Market.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_sale', to='Market.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_sale', to='Market.cashbox', verbose_name='Cashbox'),
        ),
    ]
