# Generated by Django 4.0.1 on 2022-02-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_alter_mprovider_service_and_more'),
        ('Market', '0006_transaction_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseaccept',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizations.service', verbose_name='Service'),
        ),
    ]
