# Generated by Django 3.2.7 on 2021-10-25 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_alter_product_irreducible_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='irreducible_balance',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Irreducible balance'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sale price'),
        ),
    ]
