# Generated by Django 3.2.7 on 2021-10-25 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0008_auto_20211025_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='account_money',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Account money'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='count',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price'),
        ),
    ]
