# Generated by Django 3.2.7 on 2021-10-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_auto_20211025_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='is_cash',
            field=models.BooleanField(default=1, verbose_name='Is cash'),
            preserve_default=False,
        ),
    ]
