# Generated by Django 3.2.7 on 2021-10-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_alter_organization_member_second_name'),
        ('Market', '0010_purchaserequest_is_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_purchaserequest', to='Market.cashbox', verbose_name='Cashbox'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_purchaserequest', to='Organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_purchaserequest', to='Market.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_purchaserequest', to='Organizations.service', verbose_name='Service'),
        ),
    ]
