# Generated by Django 3.2.7 on 2021-10-25 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_alter_organization_member_second_name'),
        ('Market', '0011_auto_20211025_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_purchase_request', to='Market.cashbox', verbose_name='Cashbox'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_purchase_request', to='Organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_purchase_request', to='Market.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_purchase_request', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='bank_transfer',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Bank transfer'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='card',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
    ]
