# Generated by Django 3.2.7 on 2021-10-25 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0013_alter_productorder_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price'),
        ),
    ]
