# Generated by Django 3.2.7 on 2021-10-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='clientcard',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='client',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Second name'),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Second name'),
        ),
    ]
