# Generated by Django 3.2.7 on 2021-11-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clientcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='clientcard',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=1, max_length=150, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcard',
            name='avatar',
            field=models.CharField(max_length=300, null=True, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='first_name',
            field=models.CharField(default=1, max_length=150, verbose_name='First name'),
            preserve_default=False,
        ),
    ]
