# Generated by Django 3.2.7 on 2021-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
