# Generated by Django 4.0 on 2021-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_auto_20211123_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
