# Generated by Django 3.2.7 on 2021-09-05 11:05

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='../static/Users/default-user-image.jpeg', force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='../static/Users/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='client',
            name='links',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(max_length=150, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='Surname'),
        ),
    ]
