# Generated by Django 3.2.7 on 2021-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_client_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Image'),
        ),
    ]
