# Generated by Django 4.0 on 2021-12-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_alter_clientcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='clientcard',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Avatar'),
        ),
    ]
