# Generated by Django 3.2.7 on 2021-10-01 14:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_alter_organization_description'),
        ('Clients', '0005_auto_20210905_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.CharField(max_length=300, verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Surname')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Patronymic')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone')),
                ('links', models.JSONField(null=True)),
                ('image', models.CharField(max_length=300, verbose_name='Image')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_card', to='Clients.client', verbose_name='Client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_client_card', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'ClientCard',
                'verbose_name_plural': 'ClientsCards',
                'db_table': 'ClientCard',
                'ordering': ['-updated_at'],
                'unique_together': {('organization', 'phone')},
            },
        ),
    ]
