# Generated by Django 3.2.7 on 2021-10-10 06:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_auto_20211001_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone'),
        ),
    ]
