# Generated by Django 3.2.7 on 2021-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_alter_clientcard_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
