# Generated by Django 3.2.7 on 2021-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0008_auto_20211012_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='image',
            field=models.CharField(max_length=300, null=True, verbose_name='Image'),
        ),
    ]
