# Generated by Django 3.2.7 on 2021-10-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        ('Organizations', '0001_initial'),
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_order_status', to='Organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='Clients.client', verbose_name='Client'),
        ),
    ]
