# Generated by Django 3.2.6 on 2021-08-19 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('order_code', models.BigIntegerField(verbose_name='Order_code')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Order',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'Organization',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('link', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(regex='^(https?:\\/\\/)?([\\w-]{1,32}\\.[\\w-]{1,32})[^\\s@]*$')], verbose_name='Link')),
            ],
            options={
                'verbose_name': "Organization's link",
                'verbose_name_plural': "Organizations' link",
                'db_table': 'Organization_link',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_perm_name', models.CharField(max_length=60, verbose_name='Offical_name')),
                ('name', models.CharField(max_length=150, verbose_name='Technical_name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'Permission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_services', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'Service',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to='Organizations.organization', verbose_name='Organization')),
                ('permissions', models.ManyToManyField(related_name='permission_roles', to='Organizations.Permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Role',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_numbers', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': "Organization's number",
                'verbose_name_plural': "Organizations' numbers",
                'db_table': 'Organization_number',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_members', to='Organizations.organization', verbose_name='Organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_member', to='Organizations.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Organization_member',
                'verbose_name_plural': 'Organization_members',
                'db_table': 'Organization_member',
                'ordering': ['-updated_at'],
            },
        ),
    ]
