# Generated by Django 3.2.6 on 2021-08-17 14:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'Organization',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization_link',
            fields=[
                ('mainmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Organizations.mainmixin')),
            ],
            options={
                'verbose_name': "Organization's link",
                'verbose_name_plural': "Organizations' link",
                'db_table': 'Organization_link',
                'ordering': ['-updated_at'],
            },
            bases=('Organizations.mainmixin',),
        ),
        migrations.CreateModel(
            name='Organization_number',
            fields=[
                ('mainmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Organizations.mainmixin')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
            options={
                'verbose_name': "Organization's number",
                'verbose_name_plural': "Organizations' numbers",
                'db_table': 'Organization_number',
                'ordering': ['-updated_at'],
            },
            bases=('Organizations.mainmixin',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('mainmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Organizations.mainmixin')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
            options={
                'verbose_name': "Organization's link",
                'verbose_name_plural': "Organizations' link",
                'db_table': 'Service',
                'ordering': ['-updated_at'],
            },
            bases=('Organizations.mainmixin',),
        ),
    ]
