# Generated by Django 3.2.6 on 2021-08-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
