# Generated by Django 3.2.6 on 2021-08-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompermission',
            name='official_perm_name',
        ),
        migrations.AddField(
            model_name='custompermission',
            name='codename',
            field=models.CharField(default=1, max_length=150, verbose_name='Technical_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Offical_name'),
        ),
    ]
