# Generated by Django 3.2.6 on 2021-08-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_auto_20210820_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.BigIntegerField(unique=True, verbose_name='Order_code'),
        ),
    ]
