# Generated by Django 3.2.6 on 2021-08-18 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizations', '0003_auto_20210818_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmixin',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization_link',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organization_links', to='Organizations.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization_member',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organization_members', to='Organizations.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization_number',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organization_numbers', to='Organizations.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organization_services', to='Organizations.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='organization_member',
            unique_together={('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='organization_number',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'organization')},
        ),
    ]
