# Generated by Django 3.2.6 on 2021-08-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_alter_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
