# Generated by Django 3.2.6 on 2021-08-18 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_auto_20210818_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_link',
            name='link',
            field=models.CharField(default=1, max_length=200, validators=[django.core.validators.RegexValidator(regex='^(https?:\\/\\/)?([\\w-]{1,32}\\.[\\w-]{1,32})[^\\s@]*$')], verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='organization_link',
            unique_together={('link', 'organization')},
        ),
    ]
