# Generated by Django 3.2.6 on 2021-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_auto_20210825_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization_link',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Organization link', 'verbose_name_plural': 'Organizations links'},
        ),
        migrations.AlterModelOptions(
            name='organization_member',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Organization member', 'verbose_name_plural': 'Organizations members'},
        ),
        migrations.AlterModelOptions(
            name='organization_number',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Organization number', 'verbose_name_plural': 'Organizations numbers'},
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='codename',
            field=models.CharField(max_length=150, unique=True, verbose_name='Codename'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Official_name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='custompermission',
            unique_together={('name', 'codename')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'organization')},
        ),
    ]
