# Generated by Django 3.2.6 on 2021-08-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_auto_20210825_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_member',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_member', to='Organizations.role', verbose_name='Role'),
        ),
    ]
