# Generated by Django 3.2.7 on 2021-09-05 07:41

from django.db import migrations, models
import django_resized.forms
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Surname')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Patronymic')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Number')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='../static/Users/default-user-image.jpeg', force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='../static/Users/', verbose_name='Image')),
                ('links', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('confirmed_phone', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client',
                'ordering': ['-updated_at'],
            },
        ),
    ]
