# Generated by Django 3.2.6 on 2021-08-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='small_image',
        ),
    ]
