# Generated by Django 3.2.6 on 2021-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210822_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyinfo',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
