# Generated by Django 3.2.6 on 2021-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_verifyinfo_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmed',
            new_name='confirmed_email',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed_number',
            field=models.BooleanField(default=False),
        ),
    ]
