# Generated by Django 3.2.6 on 2021-08-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20210825_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifyinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'VerifyInfo', 'verbose_name_plural': 'VerifyInfoes'},
        ),
        migrations.RenameField(
            model_name='verifyinfo',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
