# Generated by Django 3.2.7 on 2021-10-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerifyInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyinfouser',
            name='type_code',
            field=models.CharField(choices=[(0, 'phone'), (1, 'email'), (2, 'reset')], max_length=10, verbose_name='Type_code'),
        ),
    ]
