# Generated by Django 3.2.7 on 2021-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=150, verbose_name='Device')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
            ],
            options={
                'verbose_name': 'Session client',
                'verbose_name_plural': 'Sessions clients',
                'db_table': 'Session_client',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Session_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=150, verbose_name='Device')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
            ],
            options={
                'verbose_name': 'Session user',
                'verbose_name_plural': 'Sessions users',
                'db_table': 'Session_user',
                'ordering': ['-updated_at'],
            },
        ),
    ]
