# Generated by Django 4.0.1 on 2022-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('data', models.JSONField(blank=True, null=True)),
                ('order_code', models.CharField(max_length=300, unique=True, verbose_name='Order_code')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('device_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='DeviceType')),
                ('device_maker', models.CharField(blank=True, max_length=300, null=True, verbose_name='DeviceMaker')),
                ('device_model', models.CharField(blank=True, max_length=300, null=True, verbose_name='DeviceModel')),
                ('device_kit', models.TextField(blank=True, null=True, verbose_name='DeviceKit')),
                ('device_appearance', models.TextField(blank=True, null=True, verbose_name='DeviceAppearance')),
                ('device_defect', models.TextField(blank=True, null=True, verbose_name='DeviceDefect')),
                ('done', models.BooleanField(default=False)),
                ('is_rush', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('color', models.CharField(max_length=150, null=True, verbose_name='Color')),
                ('icon', models.CharField(max_length=300, null=True, verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('0', 'New'), ('1', 'Pending'), ('2', 'In progress'), ('3', 'Completed'), ('4', 'Issued')], max_length=150, null=True, verbose_name='Type')),
                ('is_default', models.BooleanField(default=True)),
                ('is_payment_required', models.BooleanField(default=False)),
                ('is_comment_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OrderStatus',
                'verbose_name_plural': 'OrderStatuses',
                'db_table': 'orderstatus',
                'ordering': ['-updated_at'],
            },
        ),
    ]
