# Generated by Django 3.2.7 on 2021-09-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_initial'),
        ('Orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_orders', to='Organizations.organization', verbose_name='Organization'),
        ),
    ]
