# Generated by Django 3.2.7 on 2021-10-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='device_appearance',
            field=models.TextField(blank=True, null=True, verbose_name='DeviceAppearance'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_defect',
            field=models.TextField(blank=True, null=True, verbose_name='DeviceDefect'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_kit',
            field=models.TextField(blank=True, null=True, verbose_name='DeviceKit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_maker',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='DeviceMaker'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_model',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='DeviceModel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_type',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='DeviceType'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='type',
            field=models.CharField(choices=[('0', 'New'), ('1', 'Pending'), ('2', 'In progress'), ('3', 'Completed'), ('4', 'Issued')], max_length=150, null=True, verbose_name='Type'),
        ),
    ]
