# Generated by Django 4.0.1 on 2022-02-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_alter_mprovider_service_and_more'),
        ('Orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orderstatuses', to='Organizations.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='Organizations.service', verbose_name='Service'),
        ),
    ]
