# Generated by Django 3.2.7 on 2021-09-05 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clients', '0003_alter_client_phone'),
        ('Organizations', '0002_initial'),
        ('Orders', '0003_order_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='Clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_executor', to='Users.user', verbose_name='Executor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_orders', to='Organizations.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='Organizations.service', verbose_name='Service'),
            preserve_default=False,
        ),
    ]
