# Generated by Django 3.2.7 on 2021-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20211021_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='type',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Issued', 'Issued')], max_length=150, null=True, verbose_name='Type'),
        ),
    ]
