# Generated by Django 3.2.7 on 2021-09-05 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clients', '0003_alter_client_phone'),
        ('Orders', '0004_auto_20210905_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='Clients.client', verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_creator', to='Users.user', verbose_name='Creator'),
            preserve_default=False,
        ),
    ]
