# Generated by Django 3.2.7 on 2021-10-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_alter_organization_description'),
        ('Orders', '0005_auto_20210905_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device_appearance',
            field=models.TextField(null=True, verbose_name='DeviceAppearance'),
        ),
        migrations.AddField(
            model_name='order',
            name='device_defect',
            field=models.TextField(null=True, verbose_name='DeviceDefect'),
        ),
        migrations.AddField(
            model_name='order',
            name='device_kit',
            field=models.TextField(null=True, verbose_name='DeviceKit'),
        ),
        migrations.AddField(
            model_name='order',
            name='device_maker',
            field=models.CharField(max_length=300, null=True, verbose_name='DeviceMaker'),
        ),
        migrations.AddField(
            model_name='order',
            name='device_model',
            field=models.CharField(max_length=300, null=True, verbose_name='DeviceModel'),
        ),
        migrations.AddField(
            model_name='order',
            name='device_type',
            field=models.CharField(max_length=300, null=True, verbose_name='DeviceType'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_rush',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('color', models.CharField(max_length=150, null=True, verbose_name='Color')),
                ('icon', models.CharField(max_length=300, null=True, verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[(0, 'New'), (1, 'Pending'), (2, 'In progress'), (3, 'Pending'), (4, 'Completed'), (5, 'Issued')], max_length=150, null=True, verbose_name='Type')),
                ('is_default', models.BooleanField(default=True)),
                ('is_payment_required', models.BooleanField(default=False)),
                ('is_comment_required', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_order_status', to='Organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'OrderStatus',
                'verbose_name_plural': 'OrderStatuses',
                'db_table': 'OrderStatus',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_status_order', to='Orders.orderstatus', verbose_name='OrderStatus'),
        ),
    ]
