# Generated by Django 3.2.7 on 2021-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_auto_20211008_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
