# Generated by Django 3.2.7 on 2021-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_auto_20211012_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='is_comment_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='is_payment_required',
            field=models.BooleanField(default=True),
        ),
    ]
