# Generated by Django 3.2.7 on 2021-10-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_auto_20211012_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='is_comment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='is_payment_required',
            field=models.BooleanField(default=False),
        ),
    ]
