# Generated by Django 3.2.7 on 2021-10-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_auto_20211017_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=300, unique=True, verbose_name='Order_code'),
        ),
    ]
